server:
    port: 8099
spring:
    application:
        name: core
    rabbitmq:
      addresses: 127.0.0.1:5672
      username: admin
      password: mypass
      virtualHost: /
      binding:
              exchanges:
                   - name: ${spring.application.name}
                     schema:
                      fanout:
                          autoCreateQueue: true
     #                  topics:
      #                     - name: abc.test
       #                      queues: queue1