spring:
  application:
    name: example
  rabbitmq:
    addresses: 127.0.0.1:5672
    username: admin
    password: mypass
    virtualHost: /
    binding:
        exchanges:
              - name: ${spring.application.name}
                schema:
                  fanout:
                    autoCreateQueue: true
  redis:
      hostName: 127.0.0.1
      port: 6379
      password: mypass
      pool:
           maxActive: 8
           maxWait: -1
           maxIdle: 8
           minIdle: 0
           timeout: 0
server:
   port: 8080
   context-path: /service_01
eureka:
   client:
      serviceUrl:
         defaultZone: http://192.168.100.97:8761/eureka,http://192.168.100.97:8762/eureka
   instance:
      statusPageUrlPath: ${server.contextPath}/info
      healthCheckUrlPath: ${server.contextPath}/health
      preferIpAddress: true
      metadataMap:
          instanceId: ${spring.application.name}:${random.value}

