spring:
  application:
    name: example
  rabbitmq:
    addresses: 192.168.100.233:5672
    username: admin
    password: mypass
    virtualHost: /
    binding:
        exchanges:
              - name: ${spring.application.name}
                schema:
                  fanout:
                    autoCreateQueue: true
server:
   port: 8080
   context-path: /service_01
eureka:
   client:
      serviceUrl:
         defaultZone: http://192.168.100.97:8761/eureka,http://192.168.100.97:8762/eureka
   instance:
      statusPageUrlPath: ${server.contextPath}/info
      healthCheckUrlPath: ${server.contextPath}/health
      preferIpAddress: true
      metadataMap:
          instanceId: ${spring.application.name}:${random.value}